# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin2(object):
    def setupUi(self, Formwin2):
        Formwin2.setObjectName("Formwin2")
        Formwin2.resize(1100, 800)
        Formwin2.setMinimumSize(QtCore.QSize(1100, 700))
        self.frame = QtWidgets.QFrame(Formwin2)
        self.frame.setGeometry(QtCore.QRect(50, 410, 811, 151))
        self.frame.setMinimumSize(QtCore.QSize(720, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 60, 721, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_tips = QtWidgets.QLabel(self.layoutWidget)
        self.label_tips.setMinimumSize(QtCore.QSize(150, 50))
        self.label_tips.setObjectName("label_tips")
        self.horizontalLayout_2.addWidget(self.label_tips)
        self.pushButton_fun0 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_fun0.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_fun0.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px")
        self.pushButton_fun0.setObjectName("pushButton_fun0")
        self.horizontalLayout_2.addWidget(self.pushButton_fun0)
        self.pushButton_fun1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_fun1.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_fun1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px")
        self.pushButton_fun1.setObjectName("pushButton_fun1")
        self.horizontalLayout_2.addWidget(self.pushButton_fun1)
        self.pushButton_fun11 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_fun11.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_fun11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px")
        self.pushButton_fun11.setObjectName("pushButton_fun11")
        self.horizontalLayout_2.addWidget(self.pushButton_fun11)
        self.layoutWidget1 = QtWidgets.QWidget(Formwin2)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 20, 1011, 361))
        self.layoutWidget1.setMinimumSize(QtCore.QSize(500, 0))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_daichuli = QtWidgets.QLabel(self.layoutWidget1)
        self.label_daichuli.setMinimumSize(QtCore.QSize(500, 0))
        self.label_daichuli.setObjectName("label_daichuli")
        self.horizontalLayout.addWidget(self.label_daichuli)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pushButton_load = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_load.setMinimumSize(QtCore.QSize(500, 50))
        self.pushButton_load.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_load.setObjectName("pushButton_load")
        self.gridLayout.addWidget(self.pushButton_load, 1, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_save.setMinimumSize(QtCore.QSize(500, 50))
        self.pushButton_save.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 1, 1, 1, 1)
        self.label_jieguo = QtWidgets.QLabel(self.layoutWidget1)
        self.label_jieguo.setMinimumSize(QtCore.QSize(500, 0))
        self.label_jieguo.setObjectName("label_jieguo")
        self.gridLayout.addWidget(self.label_jieguo, 0, 1, 1, 1)

        self.retranslateUi(Formwin2)
        QtCore.QMetaObject.connectSlotsByName(Formwin2)

    def retranslateUi(self, Formwin2):
        _translate = QtCore.QCoreApplication.translate
        Formwin2.setWindowTitle(_translate("Formwin2", "Form"))
        self.label_tips.setText(_translate("Formwin2", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">操作：</span></p></body></html>"))
        self.pushButton_fun0.setText(_translate("Formwin2", "水平翻转"))
        self.pushButton_fun1.setText(_translate("Formwin2", "垂直翻转"))
        self.pushButton_fun11.setText(_translate("Formwin2", "沿xy轴翻转"))
        self.label_daichuli.setText(_translate("Formwin2", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">待处理</span></p></body></html>"))
        self.pushButton_load.setText(_translate("Formwin2", "选择图片"))
        self.pushButton_save.setText(_translate("Formwin2", "保存图片"))
        self.label_jieguo.setText(_translate("Formwin2", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">结果</span></p></body></html>"))
