# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin7.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin7(object):
    def setupUi(self, Formwin7):
        Formwin7.setObjectName("Formwin7")
        Formwin7.resize(1100, 800)
        Formwin7.setMinimumSize(QtCore.QSize(1100, 700))
        self.layoutWidget = QtWidgets.QWidget(Formwin7)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 60, 1008, 311))
        self.layoutWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_load = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_load.setMinimumSize(QtCore.QSize(400, 50))
        self.pushButton_load.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_load.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_load.setObjectName("pushButton_load")
        self.gridLayout.addWidget(self.pushButton_load, 1, 0, 1, 1)
        self.label_jieguo = QtWidgets.QLabel(self.layoutWidget)
        self.label_jieguo.setMinimumSize(QtCore.QSize(500, 0))
        self.label_jieguo.setStyleSheet("")
        self.label_jieguo.setObjectName("label_jieguo")
        self.gridLayout.addWidget(self.label_jieguo, 0, 1, 1, 1)
        self.label_daichuli = QtWidgets.QLabel(self.layoutWidget)
        self.label_daichuli.setMinimumSize(QtCore.QSize(500, 0))
        self.label_daichuli.setStyleSheet("")
        self.label_daichuli.setObjectName("label_daichuli")
        self.gridLayout.addWidget(self.label_daichuli, 0, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save.setMinimumSize(QtCore.QSize(400, 50))
        self.pushButton_save.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Formwin7)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 400, 661, 111))
        self.layoutWidget1.setMinimumSize(QtCore.QSize(80, 50))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_xiufu = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_xiufu.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_xiufu.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:30px;")
        self.pushButton_xiufu.setObjectName("pushButton_xiufu")
        self.horizontalLayout.addWidget(self.pushButton_xiufu)
        self.pushButton_SRGAN = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_SRGAN.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_SRGAN.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:30px;")
        self.pushButton_SRGAN.setObjectName("pushButton_SRGAN")
        self.horizontalLayout.addWidget(self.pushButton_SRGAN)
        self.pushButton_MPRnet = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_MPRnet.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_MPRnet.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:30px;")
        self.pushButton_MPRnet.setObjectName("pushButton_MPRnet")
        self.horizontalLayout.addWidget(self.pushButton_MPRnet)
        self.pushButton_DeblurGan = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_DeblurGan.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_DeblurGan.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:30px;")
        self.pushButton_DeblurGan.setObjectName("pushButton_DeblurGan")
        self.horizontalLayout.addWidget(self.pushButton_DeblurGan)
        self.pushButton_Deblurganv2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_Deblurganv2.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_Deblurganv2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.pushButton_Deblurganv2.setObjectName("pushButton_Deblurganv2")
        self.horizontalLayout.addWidget(self.pushButton_Deblurganv2)

        self.retranslateUi(Formwin7)
        QtCore.QMetaObject.connectSlotsByName(Formwin7)

    def retranslateUi(self, Formwin7):
        _translate = QtCore.QCoreApplication.translate
        Formwin7.setWindowTitle(_translate("Formwin7", "Form"))
        self.pushButton_load.setText(_translate("Formwin7", "选择图片"))
        self.label_jieguo.setText(_translate("Formwin7", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">结果</span></p></body></html>"))
        self.label_daichuli.setText(_translate("Formwin7", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">待处理</span></p></body></html>"))
        self.pushButton_save.setText(_translate("Formwin7", "保存图片"))
        self.pushButton_xiufu.setText(_translate("Formwin7", "图像修复"))
        self.pushButton_SRGAN.setText(_translate("Formwin7", "SRGAN"))
        self.pushButton_MPRnet.setText(_translate("Formwin7", "MPRNet"))
        self.pushButton_DeblurGan.setText(_translate("Formwin7", "DeblurGan"))
        self.pushButton_Deblurganv2.setText(_translate("Formwin7", "DeblurGan-v2"))
