# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin5(object):
    def setupUi(self, Formwin5):
        Formwin5.setObjectName("Formwin5")
        Formwin5.resize(1100, 700)
        Formwin5.setMinimumSize(QtCore.QSize(1100, 700))
        Formwin5.setMaximumSize(QtCore.QSize(1100, 700))
        self.layoutWidget = QtWidgets.QWidget(Formwin5)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 40, 714, 622))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_daichuli = QtWidgets.QLabel(self.layoutWidget)
        self.label_daichuli.setMinimumSize(QtCore.QSize(500, 250))
        self.label_daichuli.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_daichuli.setStyleSheet("")
        self.label_daichuli.setObjectName("label_daichuli")
        self.gridLayout.addWidget(self.label_daichuli, 0, 0, 1, 1)
        self.pushButton_load = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_load.setMinimumSize(QtCore.QSize(500, 50))
        self.pushButton_load.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_load.setObjectName("pushButton_load")
        self.gridLayout.addWidget(self.pushButton_load, 1, 0, 1, 1)
        self.label_jieguo = QtWidgets.QLabel(self.layoutWidget)
        self.label_jieguo.setMinimumSize(QtCore.QSize(500, 250))
        self.label_jieguo.setStyleSheet("")
        self.label_jieguo.setObjectName("label_jieguo")
        self.gridLayout.addWidget(self.label_jieguo, 2, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save.setMinimumSize(QtCore.QSize(500, 50))
        self.pushButton_save.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 3, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setMinimumSize(QtCore.QSize(40, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 0, 158, 580))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_zhongzhi = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_zhongzhi.setMinimumSize(QtCore.QSize(150, 60))
        self.pushButton_zhongzhi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.pushButton_zhongzhi.setObjectName("pushButton_zhongzhi")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_zhongzhi)
        self.pushButton_gauss = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_gauss.setMinimumSize(QtCore.QSize(150, 60))
        self.pushButton_gauss.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.pushButton_gauss.setObjectName("pushButton_gauss")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_gauss)
        self.pushButton_fangbo = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_fangbo.setMinimumSize(QtCore.QSize(150, 60))
        self.pushButton_fangbo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.pushButton_fangbo.setObjectName("pushButton_fangbo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_fangbo)
        self.pushButton_junzhi = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_junzhi.setMinimumSize(QtCore.QSize(150, 60))
        self.pushButton_junzhi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.pushButton_junzhi.setObjectName("pushButton_junzhi")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_junzhi)
        self.pushButton_suangbian = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_suangbian.setMinimumSize(QtCore.QSize(150, 60))
        self.pushButton_suangbian.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.pushButton_suangbian.setObjectName("pushButton_suangbian")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton_suangbian)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Formwin5)
        QtCore.QMetaObject.connectSlotsByName(Formwin5)

    def retranslateUi(self, Formwin5):
        _translate = QtCore.QCoreApplication.translate
        Formwin5.setWindowTitle(_translate("Formwin5", "Form"))
        self.label_daichuli.setText(_translate("Formwin5", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">待处理</span></p></body></html>"))
        self.pushButton_load.setText(_translate("Formwin5", "选择图片"))
        self.label_jieguo.setText(_translate("Formwin5", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">结果</span></p></body></html>"))
        self.pushButton_save.setText(_translate("Formwin5", "保存图片"))
        self.pushButton_zhongzhi.setText(_translate("Formwin5", "中值滤波"))
        self.pushButton_gauss.setText(_translate("Formwin5", "高斯滤波"))
        self.pushButton_fangbo.setText(_translate("Formwin5", "方波滤波"))
        self.pushButton_junzhi.setText(_translate("Formwin5", "均值滤波"))
        self.pushButton_suangbian.setText(_translate("Formwin5", "双边滤波"))
