# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin1(object):
    def setupUi(self, Formwin1):
        Formwin1.setObjectName("Formwin1")
        Formwin1.resize(1100, 800)
        Formwin1.setMinimumSize(QtCore.QSize(1100, 800))
        self.layoutWidget = QtWidgets.QWidget(Formwin1)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 50, 1008, 311))
        self.layoutWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_load = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_load.setMinimumSize(QtCore.QSize(400, 50))
        self.pushButton_load.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_load.setObjectName("pushButton_load")
        self.gridLayout.addWidget(self.pushButton_load, 1, 0, 1, 1)
        self.label_jieguo = QtWidgets.QLabel(self.layoutWidget)
        self.label_jieguo.setMinimumSize(QtCore.QSize(500, 0))
        self.label_jieguo.setObjectName("label_jieguo")
        self.gridLayout.addWidget(self.label_jieguo, 0, 1, 1, 1)
        self.label_daichuli = QtWidgets.QLabel(self.layoutWidget)
        self.label_daichuli.setMinimumSize(QtCore.QSize(500, 0))
        self.label_daichuli.setObjectName("label_daichuli")
        self.gridLayout.addWidget(self.label_daichuli, 0, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save.setMinimumSize(QtCore.QSize(400, 50))
        self.pushButton_save.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Formwin1)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 390, 661, 111))
        self.layoutWidget1.setMinimumSize(QtCore.QSize(80, 50))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_turntoGray = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_turntoGray.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_turntoGray.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px")
        self.pushButton_turntoGray.setObjectName("pushButton_turntoGray")
        self.horizontalLayout.addWidget(self.pushButton_turntoGray)
        self.pushButton_turntotwo = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_turntotwo.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_turntotwo.setStyleSheet("border-radius:30px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_turntotwo.setObjectName("pushButton_turntotwo")
        self.horizontalLayout.addWidget(self.pushButton_turntotwo)

        self.retranslateUi(Formwin1)
        QtCore.QMetaObject.connectSlotsByName(Formwin1)

    def retranslateUi(self, Formwin1):
        _translate = QtCore.QCoreApplication.translate
        Formwin1.setWindowTitle(_translate("Formwin1", "Form"))
        self.pushButton_load.setText(_translate("Formwin1", "选择图片"))
        self.label_jieguo.setText(_translate("Formwin1", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">结果</span></p></body></html>"))
        self.label_daichuli.setText(_translate("Formwin1", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">待处理</span></p></body></html>"))
        self.pushButton_save.setText(_translate("Formwin1", "保存图片"))
        self.pushButton_turntoGray.setText(_translate("Formwin1", "转成灰度图"))
        self.pushButton_turntotwo.setText(_translate("Formwin1", "将图片二值化"))
