# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin3(object):
    def setupUi(self, Formwin3):
        Formwin3.setObjectName("Formwin3")
        Formwin3.resize(1100, 800)
        Formwin3.setMinimumSize(QtCore.QSize(1100, 700))
        self.layoutWidget = QtWidgets.QWidget(Formwin3)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 50, 1008, 311))
        self.layoutWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_load = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_load.setMinimumSize(QtCore.QSize(400, 50))
        self.pushButton_load.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_load.setObjectName("pushButton_load")
        self.gridLayout.addWidget(self.pushButton_load, 1, 0, 1, 1)
        self.label_jieguo = QtWidgets.QLabel(self.layoutWidget)
        self.label_jieguo.setMinimumSize(QtCore.QSize(500, 0))
        self.label_jieguo.setObjectName("label_jieguo")
        self.gridLayout.addWidget(self.label_jieguo, 0, 1, 1, 1)
        self.label_daichuli = QtWidgets.QLabel(self.layoutWidget)
        self.label_daichuli.setMinimumSize(QtCore.QSize(500, 0))
        self.label_daichuli.setObjectName("label_daichuli")
        self.gridLayout.addWidget(self.label_daichuli, 0, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save.setMinimumSize(QtCore.QSize(400, 50))
        self.pushButton_save.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(Formwin3)
        self.frame.setGeometry(QtCore.QRect(644, 391, 16, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget1 = QtWidgets.QWidget(Formwin3)
        self.layoutWidget1.setGeometry(QtCore.QRect(320, 400, 471, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_lap = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_lap.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_lap.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:30px")
        self.pushButton_lap.setObjectName("pushButton_lap")
        self.gridLayout_2.addWidget(self.pushButton_lap, 0, 0, 1, 1)
        self.pushButton_zhifangtu = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_zhifangtu.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_zhifangtu.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:30px")
        self.pushButton_zhifangtu.setObjectName("pushButton_zhifangtu")
        self.gridLayout_2.addWidget(self.pushButton_zhifangtu, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 10, 100, 30))
        self.label.setMinimumSize(QtCore.QSize(100, 30))
        self.label.setObjectName("label")
        self.lineEdit_power_value = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_power_value.setGeometry(QtCore.QRect(80, 20, 150, 30))
        self.lineEdit_power_value.setMinimumSize(QtCore.QSize(150, 30))
        self.lineEdit_power_value.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_power_value.setObjectName("lineEdit_power_value")
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.pushButton_gama = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_gama.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_gama.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:30px")
        self.pushButton_gama.setObjectName("pushButton_gama")
        self.gridLayout_2.addWidget(self.pushButton_gama, 1, 1, 1, 1)

        self.retranslateUi(Formwin3)
        QtCore.QMetaObject.connectSlotsByName(Formwin3)

    def retranslateUi(self, Formwin3):
        _translate = QtCore.QCoreApplication.translate
        Formwin3.setWindowTitle(_translate("Formwin3", "Form"))
        self.pushButton_load.setText(_translate("Formwin3", "选择图片"))
        self.label_jieguo.setText(_translate("Formwin3", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">结果</span></p></body></html>"))
        self.label_daichuli.setText(_translate("Formwin3", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">待处理</span></p></body></html>"))
        self.pushButton_save.setText(_translate("Formwin3", "保存图片"))
        self.pushButton_lap.setText(_translate("Formwin3", "拉普拉斯变化"))
        self.pushButton_zhifangtu.setText(_translate("Formwin3", "直方图均衡"))
        self.label.setText(_translate("Formwin3", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">power:</span></p></body></html>"))
        self.pushButton_gama.setText(_translate("Formwin3", "伽马变化"))
